//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eczane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilac
    {
        public int ilac_id { get; set; }
        public string ilac_ad { get; set; }
        public string ilac_barkod { get; set; }
        public int ilacadet { get; set; }
        public Nullable<double> ilacfiyat { get; set; }
    }
}
