//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eczane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici_yetki
    {
        public int kullanici_id { get; set; }
        public string kullanici_ad { get; set; }
        public int personel_id { get; set; }
        public string kullanici_soyad { get; set; }
        public string kullanici_email { get; set; }
        public string kullanici_sifre { get; set; }
        public string kullanicirol { get; set; }
    
        public virtual personel personel { get; set; }
    }
}
