//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eczane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eczaneEntities : DbContext
    {
        public eczaneEntities()
            : base("name=eczaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fatura> fatura { get; set; }
        public virtual DbSet<ilac> ilac { get; set; }
        public virtual DbSet<kullanici_yetki> kullanici_yetki { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<recete> recete { get; set; }
    }
}
