//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eczane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.kullanici_yetki = new HashSet<kullanici_yetki>();
        }
    
        public int personelid { get; set; }
        public string tc { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public System.DateTime dtarih { get; set; }
        public string adres { get; set; }
        public string ceptel { get; set; }
        public string diplomano { get; set; }
        public string mezuniyet { get; set; }
        public string cinsiyet { get; set; }
        public int kullanilanizin { get; set; }
        public int kalanizin { get; set; }
        public Nullable<System.DateTime> izinbitis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanici_yetki> kullanici_yetki { get; set; }
    }
}
