//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eczane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class recete
    {
        public int receteid { get; set; }
        public string hastaad { get; set; }
        public string hastatc { get; set; }
        public string ilacbarkod { get; set; }
        public string recetekodu { get; set; }
        public System.DateTime recetetarih { get; set; }
        public string ilacadet { get; set; }
        public Nullable<sbyte> ilacVerildiMi { get; set; }
    }
}
