//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilac
    {
        public int ilacid { get; set; }
        public string ilacad { get; set; }
        public string ilacicerik { get; set; }
        public string ilacbarkod { get; set; }
    }
}
