//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class izin
    {
        public int izinid { get; set; }
        public Nullable<int> personelid { get; set; }
        public Nullable<System.DateTime> izinbaslangic { get; set; }
        public Nullable<System.DateTime> izinbitis { get; set; }
        public string izindekiadres { get; set; }
        public Nullable<int> izinturu { get; set; }
        public Nullable<bool> onaylandimi { get; set; }
    
        public virtual izintur izintur { get; set; }
        public virtual personel personel { get; set; }
    }
}
