//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanici_Yetki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public kullanici_Yetki()
        {
            this.hasta = new HashSet<hasta>();
            this.islemler = new HashSet<islemler>();
            this.muayene = new HashSet<muayene>();
        }
    
        public int kullaniciid { get; set; }
        public Nullable<int> personelid { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public Nullable<bool> hastakayit { get; set; }
        public Nullable<bool> klinik { get; set; }
        public Nullable<bool> eczane { get; set; }
        public Nullable<bool> vezne { get; set; }
        public string kullaniciRol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hasta> hasta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<islemler> islemler { get; set; }
        public virtual personel personel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<muayene> muayene { get; set; }
    }
}
