//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesajgiden
    {
        public int gidenmesajid { get; set; }
        public string mesaj { get; set; }
        public Nullable<int> kimdenid { get; set; }
        public Nullable<int> kimeid { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public Nullable<int> cevaplananmesaj { get; set; }
    
        public virtual doktor doktor { get; set; }
    }
}
