//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HastaneEntities2 : DbContext
    {
        public HastaneEntities2()
            : base("name=HastaneEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<doktor> doktor { get; set; }
        public virtual DbSet<hasta> hasta { get; set; }
        public virtual DbSet<hastane> hastane { get; set; }
        public virtual DbSet<hata> hata { get; set; }
        public virtual DbSet<ilac> ilac { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<islemler> islemler { get; set; }
        public virtual DbSet<izin> izin { get; set; }
        public virtual DbSet<izintur> izintur { get; set; }
        public virtual DbSet<kanGrubu> kanGrubu { get; set; }
        public virtual DbSet<klinik> klinik { get; set; }
        public virtual DbSet<kullanici_Yetki> kullanici_Yetki { get; set; }
        public virtual DbSet<mesajgiden> mesajgiden { get; set; }
        public virtual DbSet<muayene> muayene { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<randevu> randevu { get; set; }
        public virtual DbSet<recete> recete { get; set; }
        public virtual DbSet<saat> saat { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<teshis> teshis { get; set; }
        public virtual DbSet<unvan> unvan { get; set; }
    }
}
