//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hastane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class randevu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public randevu()
        {
            this.hasta = new HashSet<hasta>();
        }
    
        public int randevuid { get; set; }
        public string adsyad { get; set; }
        public Nullable<int> hastaid { get; set; }
        public Nullable<int> saat { get; set; }
        public Nullable<int> doktorid { get; set; }
        public Nullable<int> klinikid { get; set; }
        public Nullable<bool> geldimi { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hasta> hasta { get; set; }
        public virtual saat saat1 { get; set; }
    }
}
